version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jkcart
      POSTGRES_USER: jkcart_user
      POSTGRES_PASSWORD: jkcart_pass
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
