spring:
  datasource:
    url: jdbc:postgresql://db:5432/jkcart
    username: jkcart_user
    password: jkcart_pass
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
